all: main1 main2 main3 main4

main1: main1.cpp myqueriable.h
	g++ main1.cpp -o main1 -std=c++14

main2: main2.cpp myqueriable.h
	g++ main2.cpp -o main2 -std=c++14

main3: main3.cpp myqueriable.h
	g++ main3.cpp -o main3 -std=c++14

main4: main4.cpp myqueriable.h
	g++ main4.cpp -o main4 -std=c++14

clean:
	rm main1 main2 main3 main4
